### PR TITLE
CNS block requires access to iSCSI TCP/3260 inbound.

### PR DESCRIPTION
**Pull request by jmencak**
@ekuric PTAL

### CODE REVIEW

**Comment by mbruzek** [comment]
+1 to this change.

Do we need to make a request to update this in openshift-ansible as well?

**Comment by ekuric** [comment]
gluster / cns block component requires port 3260 to be open between nodes hosting cns pods which provide gluster block feature.

**Comment by ekuric** [comment]
lgtm

**Comment by jmencak** [comment]
Yes, a follow-on PR against openshift-ansible is needed.  I'll take care of that once we have a successful install.  We've already enabled TCP/111, now 3260.  Let's have it tested properly before submitting any more PRs.  Perhaps we'll find there is need for another port...

**Comment by ekuric** [comment]
@jmencak @mbruzek I think, openshift-ansible knows how to handle ports for cns block/file properly. openshift-ansible installer set all ports for cns block/file properly

**Comment by jmencak** [comment]
@ekuric, you're right, it seems to https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_storage_glusterfs/defaults/main.yml#L101

Unfortunately, I did my openstack heat template file based on the file before all the ports were there (2018-01-30).  Will adjust once tested.

**Comment by jmencak** [comment]
Look like we're still missing TCP 24010 (glusterblockd).  Will take care of it.

**Pull request merged**
