### PR TITLE
Manage openshift example imagestreams and templates during install.

### PR DESCRIPTION
**Pull request by jmencak**
@ekuric PTAL

### CODE REVIEW

**Comment by jmencak** [comment]
@ekuric actually, isn't it the oposite, and we need both of these false?  Needs testing.

**Comment by jmencak** [comment]
Needs to be
openshift_examples_modify_imagestreams: true
openshift_examples_modify_imagestreams: false

**Comment by ekuric** [comment]
default values which will import images are 
```
openshift_install_examples=true
openshift_examples_modify_imagestreams=false 
```
in my tests they were commented / omitted -  leaving to default

**Comment by jmencak** [comment]
@mbruzek  Merging this will not hurt, but let's also try to remove
openshift_install_examples: true
openshift_examples_modify_imagestreams: false
on the next install and check ".oc get images -n openshift".  As @ekuric says, defaults should do it.

**Pull request merged**
