### PR TITLE
Adding MaxStartups to the ssh configuration.

### PR DESCRIPTION
**Pull request by mbruzek**
Please review if these values are correct.

### CODE REVIEW

**Comment by jmencak** [comment]
I've tested with these values, however I couldn't be sure they really help.  Nevertheless, I still believe they will do more right than wrong.  However, I'd rather see these changes in the image provisioner together with "UseDNS no", so that all hosts can benefit from this setting.

**Comment by mbruzek** [comment]
Please create a PR for the image provisioner to be updated with these values and link it here. I too would prefer this to be on the images.

**Comment by ashishkamra** [comment]
@chaitanyaenr ptal

**Comment by chaitanyaenr** [comment]
@mbruzek @jmencak @ashishkamra will modify image provisioner to add the options to sshd_config.

**Comment by jmencak** [comment]
@chaitanyaenr I'm happy to do that myself, just need to verify the settings help, thanks, Ravi.

**Comment by chaitanyaenr** [comment]
@jmencak makes sense to me, please go ahead and create a PR.

**Comment by mbruzek** [comment]
Closing this PR in favor of https://github.com/openshift/svt/pull/419

**Pull request closed without merging**
