### PR TITLE
Making the additional openshift_registries a variable.

### PR DESCRIPTION
**Pull request by mbruzek**
The OpenShift container registries can change and should be read from an environment variable rather than being hard coded. Using the find and replace list variable to insert these variables in the file.

### CODE REVIEW

**Comment by mbruzek** [comment]
@jmencak - I believe this PR supersedes your PR #14. Please take a look and tell me if I missed anything or if you have any review comments.

**Comment by jmencak** [comment]
@mbruzek how will variables like 'openshift_prometheus_image_version' and others that do not exist in inventory/group_vars/OSEv3.yml get replaced?

**Comment by mbruzek** [comment]
@jmencak thanks for the review. The Ansible [lineinfile module]http://docs.ansible.com/ansible/latest/lineinfile_module.html) ensures the line exists in the file even if the regex does not previously exist. That is how the module is documented to work and I have tested this behavior just to make sure.

**Comment by jmencak** [comment]
OK, tested the lineinfile module, works fine. /lgtm

**Comment by mbruzek** [comment]
When reviewing @jmencak 's work I learned to use a "^#?" at the start of the regexp in case the value exists but is commented. At this time none of these values exist but this will help prevent problems if they appear in the future. Thanks Jiri!

**Pull request merged**
