### PR TITLE
Adjusting size of m4.2xlarge sized flavor

### PR DESCRIPTION
**Pull request by akrzos**

### CODE REVIEW

**Comment by akrzos** [comment]
DNM - Do not merge yet.  I am currently testing this flavor size for the app-nodes to see if we can fit the size we need.

Thanks.

**Comment by jeremyeder** [comment]
did you really mean 1280?

**Comment by akrzos** [comment]
> did you really mean 1280?

Yes, I "added" 1024 to reduce the flavor size, so the total reduction would be 256 and 1024, but we can try out just 1024 to be a more easily explainable number too.

**Comment by akrzos** [comment]
So this fit, so we can merge now or further fine tune if we want to maximize the memory on m4.2xlarge.

**Comment by mbruzek** [comment]
I heard the discussion about this at the meeting. It sounds like this was required to fit more VMs on a compute node.

**Pull request merged**
